name: Docker

"on":
  push:
    branches:
      - main
    tags:
      - '*.*.*'

jobs:
  postgresql:
    uses: edencehealth/workflows/.github/workflows/dockerimage.yml@v1
    with:
      container_name: ohdsi-webapi_postgresql
      build-args:
        GIT_REF=${GIT_REF}
        MAVEN_PROFILE=webapi-postgresql
    secrets: inherit

  mssql:
    uses: edencehealth/workflows/.github/workflows/dockerimage.yml@v1
    with:
      container_name: ohdsi-webapi_mssql
      build-args:
        GIT_REF=${GIT_REF}
        MAVEN_PROFILE=webapi-mssql
    secrets: inherit
