name: Docker

"on":
  push:
    branches:
      - main
    tags:
      - '*.*.*'

jobs:
  # https://github.com/edencehealth/workflows
  postgresql:
    uses: edencehealth/workflows/.github/workflows/dockerimage.yml@v1
    with:
      container_name: ohdsi-webapi_postgresql
      build_args: |
        MAVEN_PROFILE=webapi-postgresql
    secrets: inherit

  # https://github.com/edencehealth/workflows
  mssql:
    uses: edencehealth/workflows/.github/workflows/dockerimage.yml@v1
    with:
      container_name: ohdsi-webapi_mssql
      build_args: |
        MAVEN_PROFILE=webapi-mssql
    secrets: inherit
