name: Docker

"on":
  push:
    branches:
      - main
    tags:
      - '*.*.*'

env:
  # for updates, see: https://github.com/OHDSI/WebAPI/releases
  UPSTREAM_GIT_REF: "refs/tags/v2.12.1"

jobs:
  postgresql:
    uses: edencehealth/workflows/.github/workflows/dockerimage.yml@v1
    with:
      container_name: ohdsi-webapi_postgresql
      build_args:
        GIT_REF=${UPSTREAM_GIT_REF}
        MAVEN_PROFILE=webapi-postgresql
    secrets: inherit

  mssql:
    uses: edencehealth/workflows/.github/workflows/dockerimage.yml@v1
    with:
      container_name: ohdsi-webapi_mssql
      build_args:
        GIT_REF=${UPSTREAM_GIT_REF}
        MAVEN_PROFILE=webapi-mssql
    secrets: inherit
